name: Deploy Inference Server

on:
  push:
    branches: [ deploy-inference-server ]
    paths:
      - 'inference_server/**'
  pull_request:
    branches: [ deploy-inference-server ]
    paths:
      - 'inference_server/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-inference-server:
    runs-on: inference-server
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies and download model
      shell: bash -l {0}
      run: |
        cd inference_server
        chmod +x ovis-setup.sh
        bash ovis-setup.sh
      
    - name: Start inference server
      run: |
        cd inference_server
        tmux new-session -d -s inference_server "conda activate ovis-env && OVIS_MODEL=Ovis/models/Ovis2-8B-GPTQ-Int4 fastapi run infer.py > inference_server.log 2>&1"